global:

  resolve_timeout: 5m

##########################################################

route:

  receiver: default

  group_by:
    - alertname
    - severity

  group_wait: 10s

  group_interval: 30s

  repeat_interval: 4h

##########################################################

receivers:

  - name: default

##########################################################
# Uncomment later for email
##########################################################

#  - name: email
#
#    email_configs:
#
#      - to: your@email.com
#
#        from: grafana@example.com
#
#        smarthost: smtp.gmail.com:587
#
#        auth_username: your@email.com
#
#        auth_password: YOUR_APP_PASSWORD
#
#        require_tls: true

##########################################################
# Uncomment later for Slack
##########################################################

#  - name: slack
#
#    slack_configs:
#
#      - api_url: https://hooks.slack.com/services/XXXX
#
#        channel: "#alerts"

##########################################################
# Uncomment later for Discord
##########################################################

#  - name: discord
#
#    webhook_configs:
#
#      - url: https://discord.com/api/webhooks/xxxx

##########################################################

inhibit_rules:

  - source_match:

      severity: critical

    target_match:

      severity: warning

    equal:

      - alertname
